# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

gems:
  - jekyll-paginate
  - jekyll-sitemap
  # Font Awesome GEM // UNUSED // see _includes/head.html
  #- font-awesome-sass

# Setup
title: Matthieu Cadet

tagline: |
    Senior Compositing Artist,
    Technical Director
    & Pipeline Developer

description: |
    Senior Compositing Artist, Technical Director & Pipeline Developer
    at <a href="http://nWave.com" target="_blank">nWave Digital</a> (Brussels, Belgium).

url:                 http://matthieucadet.info
baseurl:             ''
paginate:            5

# Comments are powered by disqus
comments: false

# Google analytics
#   ( https://analytics.google.com/
#     see _includes/analytics.html
#     which is included by _layouts/default.html )
#
tracking_id: UA-69243698-7 # GA Tracking ID

# About/contact
author:
  name:              Matthieu Cadet
  url:               http://matthieucadet.info
  email:             matthieu.cadet@gmail.com

# Custom vars
version:             1.0.0

twitter_username: maty974

github_repo: maty974.github.com
github_username: maty974
github_show_edit_link: true

linkedin_username: matthieucadet
flickr_username: maty974
#facebook_id: maty974
#instagram_username: maty974
